### ISSUE TITLE
Not able to get the Response in the Development or Also after Installing in the extension from marketplace 

### ISSUE THREAD

**Issue by satishsalesforce** [timkmecl/chatgpt-vscode#11]
Hi Team, Not sure what I am missing, I modified the required code in the chatGPT to include the fetch. But I am not able to get any response from Chatgpt and it always timeout. 

I tried the same from the marketplace to check if it is happening only in development, it happens in the actual extension in the marketplace also.

Anything I am missing here? please advise.

<img width="1790" alt="Screenshot 2023-02-11 at 08 24 47" src="https://user-images.githubusercontent.com/118750862/218248360-3cd6701e-5831-4023-847a-cc4b3c41c2e5.png">

**Comment by satishsalesforce** [comment]
@timkmecl Thanks for your update and waiting for the fix.

**Comment by timkmecl** [comment]
The extension now uses the official API released this week, so this is now fixed.
