### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by RoadieGamer** [timkmecl/chatgpt-vscode#13]
Maybe it is my API key but I am getting [ERROR] TimeoutError: ChatGPT timed out waiting for response for everything

**Comment by danyz81** [comment]
hello, still the same also to me: "[ERROR] TimeoutError: ChatGPT timed out waiting for response"

**Comment by timkmecl** [comment]
Hi, this is now fixed in today's update which now uses the official API instead of the unstable unofficial method used before.
