### ISSUE TITLE
I've been doing some testing regarding 403 errors

### ISSUE THREAD

**Issue by DarkReaper231** [timkmecl/chatgpt-vscode#7]
So I dug into it and realized that even copying cookies from browser to browser using cookie management addons is tricky. Basically It would never accept the cookie as valid and just show me login page. But I made a breakthrough.

![image](https://user-images.githubusercontent.com/38611351/210048930-dfda998f-c518-4676-b084-a231f84d08fb.png)

It seems that all these 3 cookies are essential to get logged. For example callback-url value if not same as it was with that specific session token will invalidate the session token. Host auth token also is important. And one BIG important thing is that all three cookies NEED to have Lax sameSite policy and they NEED to be Session cookies. Now surprisingly you don't need expiration date on the session token. 

Also the cloudflare cookies are supposed to be on `.chat.openai.com` domain, the dot is also important it seems. Other than that you only need cf_clearance, the other two cookies will get generated again.

So yeah just the session token isn't enough

**Comment by timkmecl** [comment]
Hi, thanks a lot for sharing your experiment! I will look into this.
