### ISSUE TITLE
Ideal solution to make this extension work without Errors

### ISSUE THREAD

**Issue by Welding-Torch** [timkmecl/chatgpt-vscode#8]
Hi Tim,

There's this other extension called [vscode-chatgpt](https://marketplace.visualstudio.com/items?itemName=gencay.vscode-chatgpt&ssr=false) that has solved [the Puppeteer issue ](https://github.com/timkmecl/chatgpt-vscode/issues/6#issuecomment-1356843993) and allows users to use this extension by running another window of Chrome in the background. 

I tried it myself today, and it works quite well as it also allowed me to manually solve the captcha, and then it entered my username and password for me. 

However, the problem with this other extension is that I really don't like their UI/UX and would vastly prefer the simpler experience of your extension.

Perhaps you could consider their approach of solving this problem and implement it yourself in this extension.

Kind regards,
(And I hope you had a happy holiday season ❤️)
Welding-Torch

**Comment by timkmecl** [comment]
Hi,

Thank you for letting me know about this. 
I will see if I manage to implement something like this myself once I have the time.

Thank you for your kind words and I hope you had a great holiday season as well.

Best regards,
Tim

**Comment by timkmecl** [comment]
@Welding-Torch This has now been solved using a method described in [this tweet](https://twitter.com/GodlyIgnorance/status/1620270384150093825) (simple Node.js implementation [here](https://github.com/timkmecl/chatgpt-api-wrapper)), already implemented in the unofficial chatgpt api. Only the official API key from OpenAI needed.
