### ISSUE TITLE
Activation of extension failing when debugging

### ISSUE THREAD

**Issue by aleksandr-vin** [timkmecl/chatgpt-vscode#9]
Steps to reproduce:
1. Download the source code
2. Open in vscode
3. Run `yarn install`
4. Hit `F5` to debug it
5. In the new vscode window, click on the ChatGPT extension icon on the dock

Error:
```
Activating extension 'timkmecl.chatgpt' failed: ENOENT: no such file or directory, open '/Users/jay/Downloads/chatgpt-vscode-main/dist/encoder.json'.
```

How do you debug it?

**Comment by aleksandr-vin** [comment]
This is a workaround, I've found: copy files from node_modules/gpt-3-encoder:
```
cp node_modules/gpt-3-encoder/{encoder.json,vocab.bpe} dist/
```

**Comment by timkmecl** [comment]
Hi, thank you for opening this issue. Your workaround is exactly what I did, I will update the readme to share this information. Sorry for not including this before.

**Comment by timkmecl** [comment]
I updated the README so I'm closing this issue. Thanks again!
